// Generated by gencpp from file server_io_pkg/diftorder.msg
// DO NOT EDIT!


#ifndef SERVER_IO_PKG_MESSAGE_DIFTORDER_H
#define SERVER_IO_PKG_MESSAGE_DIFTORDER_H

#include <ros/service_traits.h>


#include <server_io_pkg/diftorderRequest.h>
#include <server_io_pkg/diftorderResponse.h>


namespace server_io_pkg
{

struct diftorder
{

typedef diftorderRequest Request;
typedef diftorderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct diftorder
} // namespace server_io_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_io_pkg::diftorder > {
  static const char* value()
  {
    return "e02c72c1210af7da24f1a6fd961ebe93";
  }

  static const char* value(const ::server_io_pkg::diftorder&) { return value(); }
};

template<>
struct DataType< ::server_io_pkg::diftorder > {
  static const char* value()
  {
    return "server_io_pkg/diftorder";
  }

  static const char* value(const ::server_io_pkg::diftorder&) { return value(); }
};


// service_traits::MD5Sum< ::server_io_pkg::diftorderRequest> should match
// service_traits::MD5Sum< ::server_io_pkg::diftorder >
template<>
struct MD5Sum< ::server_io_pkg::diftorderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_io_pkg::diftorder >::value();
  }
  static const char* value(const ::server_io_pkg::diftorderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_io_pkg::diftorderRequest> should match
// service_traits::DataType< ::server_io_pkg::diftorder >
template<>
struct DataType< ::server_io_pkg::diftorderRequest>
{
  static const char* value()
  {
    return DataType< ::server_io_pkg::diftorder >::value();
  }
  static const char* value(const ::server_io_pkg::diftorderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_io_pkg::diftorderResponse> should match
// service_traits::MD5Sum< ::server_io_pkg::diftorder >
template<>
struct MD5Sum< ::server_io_pkg::diftorderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_io_pkg::diftorder >::value();
  }
  static const char* value(const ::server_io_pkg::diftorderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_io_pkg::diftorderResponse> should match
// service_traits::DataType< ::server_io_pkg::diftorder >
template<>
struct DataType< ::server_io_pkg::diftorderResponse>
{
  static const char* value()
  {
    return DataType< ::server_io_pkg::diftorder >::value();
  }
  static const char* value(const ::server_io_pkg::diftorderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_IO_PKG_MESSAGE_DIFTORDER_H
