// Generated by gencpp from file server_io_pkg/diftorderRequest.msg
// DO NOT EDIT!


#ifndef SERVER_IO_PKG_MESSAGE_DIFTORDERREQUEST_H
#define SERVER_IO_PKG_MESSAGE_DIFTORDERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_io_pkg
{
template <class ContainerAllocator>
struct diftorderRequest_
{
  typedef diftorderRequest_<ContainerAllocator> Type;

  diftorderRequest_()
    : option(0)  {
    }
  diftorderRequest_(const ContainerAllocator& _alloc)
    : option(0)  {
  (void)_alloc;
    }



   typedef uint16_t _option_type;
  _option_type option;





  typedef boost::shared_ptr< ::server_io_pkg::diftorderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_io_pkg::diftorderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct diftorderRequest_

typedef ::server_io_pkg::diftorderRequest_<std::allocator<void> > diftorderRequest;

typedef boost::shared_ptr< ::server_io_pkg::diftorderRequest > diftorderRequestPtr;
typedef boost::shared_ptr< ::server_io_pkg::diftorderRequest const> diftorderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_io_pkg::diftorderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_io_pkg::diftorderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server_io_pkg::diftorderRequest_<ContainerAllocator1> & lhs, const ::server_io_pkg::diftorderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.option == rhs.option;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server_io_pkg::diftorderRequest_<ContainerAllocator1> & lhs, const ::server_io_pkg::diftorderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server_io_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::server_io_pkg::diftorderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_io_pkg::diftorderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_io_pkg::diftorderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_io_pkg::diftorderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_io_pkg::diftorderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_io_pkg::diftorderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_io_pkg::diftorderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af74275f9217ebe12d60559909b3a954";
  }

  static const char* value(const ::server_io_pkg::diftorderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf74275f9217ebe1ULL;
  static const uint64_t static_value2 = 0x2d60559909b3a954ULL;
};

template<class ContainerAllocator>
struct DataType< ::server_io_pkg::diftorderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_io_pkg/diftorderRequest";
  }

  static const char* value(const ::server_io_pkg::diftorderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_io_pkg::diftorderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 option\n"
;
  }

  static const char* value(const ::server_io_pkg::diftorderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_io_pkg::diftorderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.option);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct diftorderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_io_pkg::diftorderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server_io_pkg::diftorderRequest_<ContainerAllocator>& v)
  {
    s << indent << "option: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.option);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_IO_PKG_MESSAGE_DIFTORDERREQUEST_H
