// Generated by gencpp from file server_io_pkg/diftorderResponse.msg
// DO NOT EDIT!


#ifndef SERVER_IO_PKG_MESSAGE_DIFTORDERRESPONSE_H
#define SERVER_IO_PKG_MESSAGE_DIFTORDERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_io_pkg
{
template <class ContainerAllocator>
struct diftorderResponse_
{
  typedef diftorderResponse_<ContainerAllocator> Type;

  diftorderResponse_()
    : state(0)  {
    }
  diftorderResponse_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint16_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::server_io_pkg::diftorderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_io_pkg::diftorderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct diftorderResponse_

typedef ::server_io_pkg::diftorderResponse_<std::allocator<void> > diftorderResponse;

typedef boost::shared_ptr< ::server_io_pkg::diftorderResponse > diftorderResponsePtr;
typedef boost::shared_ptr< ::server_io_pkg::diftorderResponse const> diftorderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_io_pkg::diftorderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_io_pkg::diftorderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server_io_pkg::diftorderResponse_<ContainerAllocator1> & lhs, const ::server_io_pkg::diftorderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server_io_pkg::diftorderResponse_<ContainerAllocator1> & lhs, const ::server_io_pkg::diftorderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server_io_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::server_io_pkg::diftorderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_io_pkg::diftorderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_io_pkg::diftorderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_io_pkg::diftorderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_io_pkg::diftorderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_io_pkg::diftorderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_io_pkg::diftorderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "891b541ef99af7889d0f22a062410be8";
  }

  static const char* value(const ::server_io_pkg::diftorderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x891b541ef99af788ULL;
  static const uint64_t static_value2 = 0x9d0f22a062410be8ULL;
};

template<class ContainerAllocator>
struct DataType< ::server_io_pkg::diftorderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_io_pkg/diftorderResponse";
  }

  static const char* value(const ::server_io_pkg::diftorderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_io_pkg::diftorderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 state\n"
"\n"
;
  }

  static const char* value(const ::server_io_pkg::diftorderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_io_pkg::diftorderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct diftorderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_io_pkg::diftorderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server_io_pkg::diftorderResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_IO_PKG_MESSAGE_DIFTORDERRESPONSE_H
