# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from server_io_pkg/data.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class data(genpy.Message):
  _md5sum = "8eafbed3b402bae6038c14d1654d8886"
  _type = "server_io_pkg/data"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time servertime
uint16 serverstate
uint32[] raw_loadcell
"""
  __slots__ = ['servertime','serverstate','raw_loadcell']
  _slot_types = ['time','uint16','uint32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       servertime,serverstate,raw_loadcell

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(data, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.servertime is None:
        self.servertime = genpy.Time()
      if self.serverstate is None:
        self.serverstate = 0
      if self.raw_loadcell is None:
        self.raw_loadcell = []
    else:
      self.servertime = genpy.Time()
      self.serverstate = 0
      self.raw_loadcell = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2IH().pack(_x.servertime.secs, _x.servertime.nsecs, _x.serverstate))
      length = len(self.raw_loadcell)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.raw_loadcell))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.servertime is None:
        self.servertime = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 10
      (_x.servertime.secs, _x.servertime.nsecs, _x.serverstate,) = _get_struct_2IH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.raw_loadcell = s.unpack(str[start:end])
      self.servertime.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2IH().pack(_x.servertime.secs, _x.servertime.nsecs, _x.serverstate))
      length = len(self.raw_loadcell)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.raw_loadcell.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.servertime is None:
        self.servertime = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 10
      (_x.servertime.secs, _x.servertime.nsecs, _x.serverstate,) = _get_struct_2IH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.raw_loadcell = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      self.servertime.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2IH = None
def _get_struct_2IH():
    global _struct_2IH
    if _struct_2IH is None:
        _struct_2IH = struct.Struct("<2IH")
    return _struct_2IH
